main/urls.py
from django.urls import path

from .views import *

app_name = 'main'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('documentation', faq_page, name='faq'),
    path('support', support_page, name='support'),
    path('create-unit', create_unit_form, name='create-unit'),
    path('list-unit', list_unit, name='list-unit'),
    path('delete/<int:obj_id>', unit_delete, name='unit-delete'),
    path('update/<int:pk>', unit_update, name='unit-update'),
    path('launch-unit', launch_unit, name='launch-unit'),
    path('get-unit-log', get_log, name='unit-log'),
    path('launch-unit-refresh', launch_refresh, name='launch-refresh'),
    path('add-task', launch_unit_form, name='add-task'),
    path('task-update/<int:pk>', launch_unit_update, name='task-update'),
    path('collected-unit-data', collected_data, name='collected-unit-data'),
    path('collected-unit-data-show/<int:pk>', collected_data_show, name='data-show'),
]

upt_v2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from upt_v2.flower import FlowerProxyView

urlpatterns = [
    path('', include('main.urls')),
    FlowerProxyView.as_url(),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

logger/models.py
import logging

from django.db import models
from django.utils.translation import gettext_lazy as _
from six import python_2_unicode_compatible

from main.models import Unit

LOG_LEVELS = (
    (logging.NOTSET, _('NotSet')),
    (logging.INFO, _('Info')),
    (logging.WARNING, _('Warning')),
    (logging.DEBUG, _('Debug')),
    (logging.ERROR, _('Error')),
    (logging.FATAL, _('Fatal')),
)


@python_2_unicode_compatible
class StatusLog(models.Model):
    logger_name = models.CharField(max_length=100)
    level = models.PositiveSmallIntegerField(choices=LOG_LEVELS, default=logging.ERROR, db_index=True)
    msg = models.TextField()
    trace = models.TextField(blank=True, null=True)
    unit = models.ForeignKey(
        Unit,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    def __str__(self):
        return self.msg

    class Meta:
        ordering = ('-create_datetime',)
        verbose_name_plural = verbose_name = 'Logging'

main/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class data(models.Model):
    text = models.CharField(max_length=1024)


class Unit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256)
    createdAt = models.DateField(auto_now_add=True, blank=True, null=True)

    class Meta:
        ordering = ['id']
        indexes = [
            models.Index(fields=['nickname', 'createdAt'])
        ]


class UnitCode(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    code = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modifiedAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)


class SupportMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=32)
    text = models.TextField()
    createdAt = models.DateField(auto_now_add=True, blank=True, null=True)


class UnitData(models.Model):
    data = models.TextField(blank=True, null=True)
    unit = models.ForeignKey(
        Unit,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    createdAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)

main/forms.py
from django.forms import ModelForm, forms
from django_celery_beat.models import CrontabSchedule, PeriodicTask

from main.models import *


class SupportForm(ModelForm):
    class Meta:
        model = SupportMessage
        fields = ['name', 'email', 'text']


class UnitCreateForm(ModelForm):
    class Meta:
        model = Unit
        fields = ['nickname', 'description']

    def clean_nickname(self):
        v = self.cleaned_data['nickname']

        if Unit.objects.filter(nickname=v).exists():
            raise forms.ValidationError('A Unit nickname already exists. It mast be uniq.')

        return v


class UnitFormUpdate(ModelForm):
    disabled_fields = ('nickname', 'user')

    class Meta:
        model = Unit
        fields = ['user', 'nickname', 'description']

    def __init__(self, *args, **kwargs):
        super(UnitFormUpdate, self).__init__(*args, **kwargs)
        for field in self.disabled_fields:
            self.fields[field].disabled = True


class UnitCodeForm(ModelForm):
    class Meta:
        model = UnitCode
        fields = ['code', ]


class CrontabForm(ModelForm):
    class Meta:
        model = CrontabSchedule
        fields = '__all__'


class PeriodicTaskUpdateForm(ModelForm):
    disabled_fields = ('task', )

    class Meta:
        model = PeriodicTask
        fields = ('name', 'task', 'description', 'enabled')

    def __init__(self, *args, **kwargs):
        super(PeriodicTaskUpdateForm, self).__init__(*args, **kwargs)
        for field in self.disabled_fields:
            self.fields[field].disabled = True

main/views.py
import json

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django_celery_beat.models import PeriodicTask

from logger.models import StatusLog
from .forms import *
from .spider.utils import Function
from .tasks import *


def all_subclasses(cls):
    return set(cls.__subclasses__()).union(
        [s for c in cls.__subclasses__() for s in all_subclasses(c)])


def index(request):
    return render(request, 'index.html')


def dashboard(request):
    return render(request, 'default/dashboard.html')


def faq_page(request):
    funcs = []
    for cls in all_subclasses(Function):
        funcs.append(cls().explanation())

    return render(request, 'default/faq.html', {'data': funcs})


def support_page(request):
    if request.method == 'POST':
        support = SupportForm(request.POST)
        if support.is_valid():
            action = support.save(commit=False)
            action.user = request.user
            action.save()
            messages.success(
                request,
                'Thank you! Your query sent successfully.'
            )
            return redirect(reverse('main:support'))
    else:
        support = SupportForm()

    return render(request, 'default/support.html', {'form': support})


def create_unit_form(request):
    if request.method == 'POST':
        unit = UnitCreateForm(request.POST, prefix='unit')
        code = UnitCodeForm(request.POST, prefix='code')
        if unit.is_valid() and code.is_valid():
            action = unit.save(commit=False)
            action.user = request.user
            code = code.save(commit=False)
            action.save()
            code.unit = action
            code.save()
            messages.success(
                request,
                'Yes! Your unit created successfully.'
            )
            return redirect(reverse('main:list-unit'))
    else:
        unit = UnitCreateForm(prefix='unit')
        code = UnitCodeForm(prefix='code')

    return render(request, 'bot/create_unit.html', {'form_unit': unit, 'form_code': code})


# def create_unit_code_form(request):
#     return render(request, 'bot/create_code.html')


def list_unit(request):
    if request.user.is_superuser:
        values = Unit.objects.all()
    else:
        values = Unit.objects.filter(user=request.user)
    return render(request, 'bot/list_unit.html', {'data': values})


def unit_update(request, pk: int):
    obj = get_object_or_404(Unit, pk=pk)
    unit = UnitFormUpdate(request.POST or None, instance=obj, prefix="unit")

    obj_code = get_object_or_404(UnitCode, unit=obj)
    code = UnitCodeForm(request.POST or None, instance=obj_code, prefix="code")

    if request.method == 'POST':
        if unit.is_valid() and code.is_valid():
            unit.save()
            code.save()
            messages.success(
                request,
                'Unit was updated successfully!'
            )
            return redirect(reverse('main:list-unit'))

    return render(request, 'bot/update_unit.html', {'form_unit': unit, 'form_code': code})


def unit_delete(request, obj_id: int):
    obj = get_object_or_404(Unit, pk=obj_id)
    obj.delete()

    return redirect(reverse('main:list-unit'))


def launch_unit(request):
    user = request.user
    tasks = user.profile.tasks.all()
    return render(request, 'bot/launch_unit.html', {'data': tasks})


@csrf_exempt
def get_log(request):
    if request.is_ajax():
        unit_id = request.POST.get('id')
        log_list = StatusLog.objects.filter(unit_id=unit_id)
        html = render_to_string('default/modal-log.html', {'data': log_list})
        return HttpResponse(html)


def launch_unit_update(request, pk):
    obj = get_object_or_404(PeriodicTask, pk=pk)
    task = PeriodicTaskUpdateForm(request.POST or None, instance=obj, prefix="task")

    obj_cron = get_object_or_404(CrontabSchedule, pk=obj.crontab.pk)
    cron = CrontabForm(request.POST or None, instance=obj_cron, prefix="cron")

    if request.method == 'POST':
        if task.is_valid() and cron.is_valid():
            task.save()
            cron.save()
            messages.success(
                request,
                'Task was updated successfully!'
            )
            return redirect(reverse('main:launch-unit'))

    return render(request, 'bot/launch_task_update_form.html', {'form_task': task, 'form_cron': cron})


@csrf_exempt
def launch_refresh(request):
    if request.is_ajax():
        user = request.user
        tasks = user.profile.tasks.all()
        html = render_to_string('bot/launch_table_part.html', {'data': tasks})
        return HttpResponse(html)


@csrf_exempt
def launch_unit_form(request):
    units = Unit.objects.filter(user=request.user)

    if request.is_ajax():
        unit_id = request.POST.get('id')
        unit = Unit.objects.filter(pk=unit_id)[0]
        crontab = CrontabForm()
        html = render_to_string('bot/launch_part.html', {'value': unit, 'form': crontab})
        return HttpResponse(html)
    elif request.method == 'POST':
        POST = request.POST.copy()
        task_name = POST.pop('task_name')[0]
        task_desc = POST.pop('task_desc')[0]
        unit_id = POST.pop('unit_id')[0]
        crontab = CrontabForm(POST)
        if crontab.is_valid():
            obj_crontab = crontab.save()
            create_periodic_task(request, task_name, task_desc, obj_crontab, unit_id)
            messages.success(
                request,
                'Unit task was added successfully!'
            )
            return redirect(reverse('main:launch-unit'))

    return render(request, 'bot/launch_unit_form.html', {'data': units})


def collected_data(request):
    user_id = request.user
    unit = Unit.objects.filter(user=user_id)
    return render(request, 'bot/collected_data.html', {'data': unit})


def collected_data_show(request, pk):
    unit = Unit.objects.filter(pk=pk)[0]
    values = UnitData.objects.filter(unit_id=unit.id)
    return render(request, 'bot/collected_data_show.html', {'unit': unit, 'data': values})


def create_periodic_task(request, name, description, schedule, unit_id):
    task = PeriodicTask.objects.create(
        crontab=schedule,  # we created this above.
        name=name,  # simply describes this periodic task.
        task='main.tasks.unit_task',  # name of task.
        description=description,
        args=json.dumps(unit_id),
    )
    request.user.profile.tasks.add(task)

    return task

main/templates/default/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Dashboard |{% endblock %}

{% block custom-style %}
    <link href="{% static "/main/vendors/custom/fullcalendar/fullcalendar.bundle.css" %}" rel="stylesheet"
          type="text/css"/>
{% endblock %}

{% block body-cls %}class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed
    kt-header-mobile--fixed kt-subheader--fixed kt-subheader--enabled kt-subheader--solid kt-aside--enabled
    kt-aside--fixed kt-page--loading"{% endblock %}

{% load widget_tweaks %}

{% block body %}
    {% include 'parts/mobile-header.html' %}
    <div class="kt-grid kt-grid--hor kt-grid--root">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">

            <!-- begin:: Aside -->
            <button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
            <div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop"
                 id="kt_aside">

                <!-- begin:: Aside -->
                <div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
                    <div class="kt-aside__brand-logo">
                        <a href="{% url 'main:dashboard' %}">
                            <img alt="Logo" src="#"/>
                        </a>
                    </div>
                    <div class="kt-aside__brand-tools">
                        <button class="kt-aside__brand-aside-toggler" id="kt_aside_toggler">
								<span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                           width="24px" height="24px" viewBox="0 0 24 24" version="1.1"
                                           class="kt-svg-icon">
										<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
											<polygon id="Shape" points="0 0 24 0 24 24 0 24"/>
											<path d="M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z"
                                                  id="Path-94" fill="#000000" fill-rule="nonzero"
                                                  transform="translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11.999999) "/>
											<path d="M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z"
                                                  id="Path-94" fill="#000000" fill-rule="nonzero" opacity="0.3"
                                                  transform="translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) translate(-15.999997, -11.999999) "/>
										</g>
									</svg></span>
                            <span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                       width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
										<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
											<polygon id="Shape" points="0 0 24 0 24 24 0 24"/>
											<path d="M12.2928955,6.70710318 C11.9023712,6.31657888 11.9023712,5.68341391 12.2928955,5.29288961 C12.6834198,4.90236532 13.3165848,4.90236532 13.7071091,5.29288961 L19.7071091,11.2928896 C20.085688,11.6714686 20.0989336,12.281055 19.7371564,12.675721 L14.2371564,18.675721 C13.863964,19.08284 13.2313966,19.1103429 12.8242777,18.7371505 C12.4171587,18.3639581 12.3896557,17.7313908 12.7628481,17.3242718 L17.6158645,12.0300721 L12.2928955,6.70710318 Z"
                                                  id="Path-94" fill="#000000" fill-rule="nonzero"/>
											<path d="M3.70710678,15.7071068 C3.31658249,16.0976311 2.68341751,16.0976311 2.29289322,15.7071068 C1.90236893,15.3165825 1.90236893,14.6834175 2.29289322,14.2928932 L8.29289322,8.29289322 C8.67147216,7.91431428 9.28105859,7.90106866 9.67572463,8.26284586 L15.6757246,13.7628459 C16.0828436,14.1360383 16.1103465,14.7686056 15.7371541,15.1757246 C15.3639617,15.5828436 14.7313944,15.6103465 14.3242754,15.2371541 L9.03007575,10.3841378 L3.70710678,15.7071068 Z"
                                                  id="Path-94" fill="#000000" fill-rule="nonzero" opacity="0.3"
                                                  transform="translate(9.000003, 11.999999) rotate(-270.000000) translate(-9.000003, -11.999999) "/>
										</g>
									</svg></span>
                        </button>
                    </div>
                </div>
                <!-- end:: Aside -->

                <!-- begin:: Aside Menu -->
                {% include 'parts/aside-menu.html' %}
                <!-- end:: Aside Menu -->
            </div>
            <!-- end:: Aside -->

            <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">

                <!-- begin:: Header -->
                {% include 'parts/header.html' %}
                <!-- end:: Header -->

                <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor">
                    <!-- begin:: Content Head -->
                    {% block content-head %}
                        {% include 'parts/content-head.html' with next=None %}
                    {% endblock %}
                    <!-- end:: Content Head -->
                    <!-- begin:: Content -->
                    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
                        {% block content %}
                            <div class="col-xl">
                                <div class="row">
                                    {% if request.user.is_superuser %}
                                        <div class="col-xl-4">
                                            <div class="card card-custom bgi-no-repeat bgi-no-repeat bgi-size-cover gutter-b"
                                                 style="height: 130px; background-image: url({% static '/main/media/bg/bg-3.jpg' %})">
                                                <!--begin::Body-->
                                                <div class="card-body d-flex flex-column">
                                                    <!--begin::Title-->
                                                    <a href="/flower" target="_blank"
                                                       class="text-hover-primary font-weight-bolder font-size-h3">
                                                        <i class="fa fa-exclamation"></i> Flower
                                                    </a>
                                                    <p>Monitoring of all tasks.<br>Only for admin.</p>
                                                    <!--end::Title-->
                                                </div>
                                                <!--end::Body-->
                                            </div>
                                        </div>
                                    {% endif %}
                                    <div class="col-xl-4">
                                        <div class=" card card-custom bgi-no-repeat bgi-no-repeat bgi-size-cover
                                         gutter-b"
                                             style="height: 130px; background-image: url({% static '/main/media/bg/bg-3.jpg' %})">
                                            <!--begin::Body-->
                                            <div class="card-body d-flex flex-column">
                                                <!--begin::Title-->
                                                <a href="{% url 'main:faq' %}" target="_blank"
                                                   class="text-hover-primary font-weight-bolder font-size-h3">
                                                    <i class="fa fa-lightbulb" aria-hidden="true"></i>
                                                    Documentation
                                                </a>
                                                <p>It is recommended to be reviewed in detail for further usage</p>
                                                <!--end::Title-->
                                            </div>
                                            <!--end::Body-->
                                        </div>
                                    </div>
                                    <div class="col-xl-4">
                                        <div class="card card-custom bgi-no-repeat bgi-no-repeat bgi-size-cover gutter-b"
                                             style="height: 130px; background-image: url({% static '/main/media/bg/bg-3.jpg' %})">
                                            <!--begin::Body-->
                                            <div class="card-body d-flex flex-column">
                                                <!--begin::Title-->
                                                <a href="{% url 'main:support' %}" target="_blank"
                                                   class="text-hover-primary font-weight-bolder font-size-h3">
                                                    <i class="fa fa-shield-alt"></i> Support
                                                </a>
                                                <p>Contact us if problem or you have an idea!</p>
                                                <!--end::Title-->
                                            </div>
                                            <!--end::Body-->
                                        </div>
                                    </div>
                                </div>
                            </div>


                        {% endblock %}
                    </div>
                    <!-- end:: Content -->
                </div>

                <!-- begin:: Footer -->
                {% include 'parts/footer.html' %}
                <!-- end:: Footer -->
            </div>
        </div>
    </div>
    {% include 'parts/scroll-top.html' %}
    {#    {% include 'parts/sticky-toolbar.html' %}#}
{% endblock %}

{% block custom-script %}
    <script src="{% static "/main/js/demo1/pages/dashboard.js" %}" type="text/javascript"></script>
{% endblock %}

main/templates/default/faq.html
{% extends 'default/dashboard.html' %}

{% block title %}Documentation |{% endblock %}

{% block content-head %}
    {% include 'parts/content-head.html' with next='Documentation' %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-body p-10">
                <!--begin::Row-->
                <div class="row">
                    <div class="col-lg">
                        <h3>Documentation of existed functions</h3>
                        <div class="callout">
                            <p>It is recommended to be reviewed in detail for further usage</p>
                        </div>
                        <p></p>
                        {% for item in data %}
                            <!--begin::Tab Content-->
                            <div class="tab-content" id="{{ item.func }}" style="margin-bottom: 10px;">
                                <!--begin::Item-->
                                <div class="card border-top-0">
                                    <div class="card-header">
                                        <strong>{{ item.func|title }}</strong>
                                    </div>
                                    <div class="card-body text-dark-50 font-size-lg pl-12"><p>
                                        <b>Function: </b>{{ item.func }}</p>
                                        <p><strong>Current state: </strong>{{ item.state }}</p>
                                        <p><strong>What it can do: </strong>{{ item.can }}</p>
                                        <p><strong>How to use in code (in general): </strong>{{ item.use }}</p>
                                        <p><strong>Access in code (after using): </strong>{{ item.access }}</p>
                                    </div>
                                </div>
                                <!--end::Item-->
                            </div>
                        {% endfor %}
                        <!--end::Tab Content-->
                    </div>
                </div>
                <!--end::Row-->
            </div>
        </div>
    </div>
{% endblock %}

main/templates/default/modal-log.html
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Log</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% for item in data %}
                <p><span
                        {% if item.get_level_display == 'Info' %}
                            class="text-success"
                        {% elif  item.get_level_display == 'Error' %}
                            class="text-danger"
                        {% elif  item.get_level_display == 'Debug' %}
                            class="text-info"
                        {% elif  item.get_level_display == 'Warning' %}
                            class="text-warning"
                        {% endif %}
                >{{ item.get_level_display }}</span> {{ item.msg|slice:":19" }}
                    <mark>{{ item.msg|slice:"24:" }}</mark>
                </p>
            {% empty %}
                <p>Sorry, you have not any log messages for this task</p>
            {% endfor %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>

main/templates/default/support.html
{% extends 'default/dashboard.html' %}

{% block title %}Support |{% endblock %}

{% block content-head %}
    {% include 'parts/content-head.html' with next='Support' %}
{% endblock %}

{% load widget_tweaks %}

{% block content %}
    <div class="alert alert-light" role="alert">
        <div class="alert-text">Send us a bug or suggestion. Welcome!
        </div>
    </div>
            {% if messages %}
            <div class="alert alert-custom alert-success fade show mb-5" role="alert">
                <div class="alert-icon">
                    <i class="flaticon-like"></i>
                </div>
                {% for msg in messages %}
                    <div class="alert-text">{{ msg }}</div>
                    <p {% if msg.tags %} class="{{ msg.tags }}"{% endif %}></p>
                {% endfor %}
                <div class="alert-close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">
                            <i class="flaticon2-cross"></i>
                        </span>
                    </button>
                </div>
            </div>
        {% endif %}
    <form class="form" method="post" action="{% url 'main:support' %}">
        {% csrf_token %}
        <div class="card-body">
            <div class="form-group">
                <label>Name:</label>
                {% render_field form.name class+="form-control form-control-solid" placeholder="Enter name"%}
                {#                <input type="text" name="name" class="form-control form-control-solid" placeholder="Enter full name"/>#}
                <span class="form-text text-muted">Please enter your name</span>
            </div>
            <div class="form-group">
                <label>Email address:</label>
                {% render_field form.email class+="form-control form-control-solid" type='email' placeholder="Enter email"%}
                {#                <input type="email" name="email" class="form-control form-control-solid" placeholder="Enter email"/>#}
                <span class="form-text text-muted">We'll never share your email with anyone else</span>
            </div>
            <div class="form-group">
                <label>Message</label>
                {% render_field form.text class+="form-control form-control-solid" rows="5" placeholder="Your message"%}
                {#                <textarea name="text" class="form-control form-control-solid" rows="5" placeholder="Your message"/></textarea>#}
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary mr-2">Send</button>
        </div>

    </form>
{% endblock %}