accounts/urls.py
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('log-out', log_out, name="log-out"),
    path('sign-in', sign_in, name="sign-in"),
    path('sign-up', signup, name="sign-up"),
    # path('profile', profile, name="profile"),
    path('forgot-password', forgot_password, name="forgot-password"),
    path('password/reset_confirm/<slug:uidb64>/<slug:token>', password_reset_confirm, name="confirm_reset_password"),
    path('activate/<slug:uidb64>/<slug:token>', activate, name="activate"),
]

main/urls.py
from django.urls import path

from .views import *

app_name = 'main'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('documentation', faq_page, name='faq'),
    path('support', support_page, name='support'),
    path('create-unit', create_unit_form, name='create-unit'),
    path('list-unit', list_unit, name='list-unit'),
    path('delete/<int:obj_id>', unit_delete, name='unit-delete'),
    path('update/<int:pk>', unit_update, name='unit-update'),
    path('launch-unit', launch_unit, name='launch-unit'),
    path('get-unit-log', get_log, name='unit-log'),
    path('launch-unit-refresh', launch_refresh, name='launch-refresh'),
    path('add-task', launch_unit_form, name='add-task'),
    path('task-update/<int:pk>', launch_unit_update, name='task-update'),
    path('collected-unit-data', collected_data, name='collected-unit-data'),
    path('collected-unit-data-show/<int:pk>', collected_data_show, name='data-show'),
]

upt_v2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from upt_v2.flower import FlowerProxyView

urlpatterns = [
    path('', include('main.urls')),
    FlowerProxyView.as_url(),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class data(models.Model):
    text = models.CharField(max_length=1024)


class Unit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256)
    createdAt = models.DateField(auto_now_add=True, blank=True, null=True)

    class Meta:
        ordering = ['id']
        indexes = [
            models.Index(fields=['nickname', 'createdAt'])
        ]


class UnitCode(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    code = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modifiedAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)


class SupportMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=32)
    text = models.TextField()
    createdAt = models.DateField(auto_now_add=True, blank=True, null=True)


class UnitData(models.Model):
    data = models.TextField(blank=True, null=True)
    unit = models.ForeignKey(
        Unit,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    createdAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)

main/forms.py
from django.forms import ModelForm, forms
from django_celery_beat.models import CrontabSchedule, PeriodicTask

from main.models import *


class SupportForm(ModelForm):
    class Meta:
        model = SupportMessage
        fields = ['name', 'email', 'text']


class UnitCreateForm(ModelForm):
    class Meta:
        model = Unit
        fields = ['nickname', 'description']

    def clean_nickname(self):
        v = self.cleaned_data['nickname']

        if Unit.objects.filter(nickname=v).exists():
            raise forms.ValidationError('A Unit nickname already exists. It mast be uniq.')

        return v


class UnitFormUpdate(ModelForm):
    disabled_fields = ('nickname', 'user')

    class Meta:
        model = Unit
        fields = ['user', 'nickname', 'description']

    def __init__(self, *args, **kwargs):
        super(UnitFormUpdate, self).__init__(*args, **kwargs)
        for field in self.disabled_fields:
            self.fields[field].disabled = True


class UnitCodeForm(ModelForm):
    class Meta:
        model = UnitCode
        fields = ['code', ]


class CrontabForm(ModelForm):
    class Meta:
        model = CrontabSchedule
        fields = '__all__'


class PeriodicTaskUpdateForm(ModelForm):
    disabled_fields = ('task', )

    class Meta:
        model = PeriodicTask
        fields = ('name', 'task', 'description', 'enabled')

    def __init__(self, *args, **kwargs):
        super(PeriodicTaskUpdateForm, self).__init__(*args, **kwargs)
        for field in self.disabled_fields:
            self.fields[field].disabled = True

main/views.py
import json

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django_celery_beat.models import PeriodicTask

from logger.models import StatusLog
from .forms import *
from .spider.utils import Function
from .tasks import *


def all_subclasses(cls):
    return set(cls.__subclasses__()).union(
        [s for c in cls.__subclasses__() for s in all_subclasses(c)])


def index(request):
    return render(request, 'index.html')


def dashboard(request):
    return render(request, 'default/dashboard.html')


def faq_page(request):
    funcs = []
    for cls in all_subclasses(Function):
        funcs.append(cls().explanation())

    return render(request, 'default/faq.html', {'data': funcs})


def support_page(request):
    if request.method == 'POST':
        support = SupportForm(request.POST)
        if support.is_valid():
            action = support.save(commit=False)
            action.user = request.user
            action.save()
            messages.success(
                request,
                'Thank you! Your query sent successfully.'
            )
            return redirect(reverse('main:support'))
    else:
        support = SupportForm()

    return render(request, 'default/support.html', {'form': support})


def create_unit_form(request):
    if request.method == 'POST':
        unit = UnitCreateForm(request.POST, prefix='unit')
        code = UnitCodeForm(request.POST, prefix='code')
        if unit.is_valid() and code.is_valid():
            action = unit.save(commit=False)
            action.user = request.user
            code = code.save(commit=False)
            action.save()
            code.unit = action
            code.save()
            messages.success(
                request,
                'Yes! Your unit created successfully.'
            )
            return redirect(reverse('main:list-unit'))
    else:
        unit = UnitCreateForm(prefix='unit')
        code = UnitCodeForm(prefix='code')

    return render(request, 'bot/create_unit.html', {'form_unit': unit, 'form_code': code})


# def create_unit_code_form(request):
#     return render(request, 'bot/create_code.html')


def list_unit(request):
    if request.user.is_superuser:
        values = Unit.objects.all()
    else:
        values = Unit.objects.filter(user=request.user)
    return render(request, 'bot/list_unit.html', {'data': values})


def unit_update(request, pk: int):
    obj = get_object_or_404(Unit, pk=pk)
    unit = UnitFormUpdate(request.POST or None, instance=obj, prefix="unit")

    obj_code = get_object_or_404(UnitCode, unit=obj)
    code = UnitCodeForm(request.POST or None, instance=obj_code, prefix="code")

    if request.method == 'POST':
        if unit.is_valid() and code.is_valid():
            unit.save()
            code.save()
            messages.success(
                request,
                'Unit was updated successfully!'
            )
            return redirect(reverse('main:list-unit'))

    return render(request, 'bot/update_unit.html', {'form_unit': unit, 'form_code': code})


def unit_delete(request, obj_id: int):
    obj = get_object_or_404(Unit, pk=obj_id)
    obj.delete()

    return redirect(reverse('main:list-unit'))


def launch_unit(request):
    user = request.user
    tasks = user.profile.tasks.all()
    return render(request, 'bot/launch_unit.html', {'data': tasks})


@csrf_exempt
def get_log(request):
    if request.is_ajax():
        unit_id = request.POST.get('id')
        log_list = StatusLog.objects.filter(unit_id=unit_id)
        html = render_to_string('default/modal-log.html', {'data': log_list})
        return HttpResponse(html)


def launch_unit_update(request, pk):
    obj = get_object_or_404(PeriodicTask, pk=pk)
    task = PeriodicTaskUpdateForm(request.POST or None, instance=obj, prefix="task")

    obj_cron = get_object_or_404(CrontabSchedule, pk=obj.crontab.pk)
    cron = CrontabForm(request.POST or None, instance=obj_cron, prefix="cron")

    if request.method == 'POST':
        if task.is_valid() and cron.is_valid():
            task.save()
            cron.save()
            messages.success(
                request,
                'Task was updated successfully!'
            )
            return redirect(reverse('main:launch-unit'))

    return render(request, 'bot/launch_task_update_form.html', {'form_task': task, 'form_cron': cron})


@csrf_exempt
def launch_refresh(request):
    if request.is_ajax():
        user = request.user
        tasks = user.profile.tasks.all()
        html = render_to_string('bot/launch_table_part.html', {'data': tasks})
        return HttpResponse(html)


@csrf_exempt
def launch_unit_form(request):
    units = Unit.objects.filter(user=request.user)

    if request.is_ajax():
        unit_id = request.POST.get('id')
        unit = Unit.objects.filter(pk=unit_id)[0]
        crontab = CrontabForm()
        html = render_to_string('bot/launch_part.html', {'value': unit, 'form': crontab})
        return HttpResponse(html)
    elif request.method == 'POST':
        POST = request.POST.copy()
        task_name = POST.pop('task_name')[0]
        task_desc = POST.pop('task_desc')[0]
        unit_id = POST.pop('unit_id')[0]
        crontab = CrontabForm(POST)
        if crontab.is_valid():
            obj_crontab = crontab.save()
            create_periodic_task(request, task_name, task_desc, obj_crontab, unit_id)
            messages.success(
                request,
                'Unit task was added successfully!'
            )
            return redirect(reverse('main:launch-unit'))

    return render(request, 'bot/launch_unit_form.html', {'data': units})


def collected_data(request):
    user_id = request.user
    unit = Unit.objects.filter(user=user_id)
    return render(request, 'bot/collected_data.html', {'data': unit})


def collected_data_show(request, pk):
    unit = Unit.objects.filter(pk=pk)[0]
    values = UnitData.objects.filter(unit_id=unit.id)
    return render(request, 'bot/collected_data_show.html', {'unit': unit, 'data': values})


def create_periodic_task(request, name, description, schedule, unit_id):
    task = PeriodicTask.objects.create(
        crontab=schedule,  # we created this above.
        name=name,  # simply describes this periodic task.
        task='main.tasks.unit_task',  # name of task.
        description=description,
        args=json.dumps(unit_id),
    )
    request.user.profile.tasks.add(task)

    return task

main/templates/parts/aside-menu.html
<div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
    <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1"
         data-ktmenu-dropdown-timeout="500">
        <ul class="kt-menu__nav ">
            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">
                <a href="{% url 'main:dashboard' %}" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                         <i class="fa fa-layer-group"></i>
                    </span>
                    <span class="kt-menu__link-text">Dashboard</span>
                </a>
            </li>
{#            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">#}
{#                <a href="{% url 'main:faq' %}" class="kt-menu__link ">#}
{#                    <span class="kt-menu__link-icon">#}
{#                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"#}
{#                             height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">#}
{#                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">#}
{#                                <rect x="0" y="0" width="24" height="24"/>#}
{#                                <circle fill="#000000" opacity="0.3" cx="12" cy="9" r="8"/>#}
{#                                <path d="M14.5297296,11 L9.46184488,11 L11.9758349,17.4645458 L14.5297296,11 Z M10.5679953,19.3624463 L6.53815512,9 L17.4702704,9 L13.3744964,19.3674279 L11.9759405,18.814912 L10.5679953,19.3624463 Z"#}
{#                                      fill="#000000" fill-rule="nonzero" opacity="0.3"/>#}
{#                                <path d="M10,22 L14,22 L14,22 C14,23.1045695 13.1045695,24 12,24 L12,24 C10.8954305,24 10,23.1045695 10,22 Z"#}
{#                                      fill="#000000" opacity="0.3"/>#}
{#                                <path d="M9,20 C8.44771525,20 8,19.5522847 8,19 C8,18.4477153 8.44771525,18 9,18 C8.44771525,18 8,17.5522847 8,17 C8,16.4477153 8.44771525,16 9,16 L15,16 C15.5522847,16 16,16.4477153 16,17 C16,17.5522847 15.5522847,18 15,18 C15.5522847,18 16,18.4477153 16,19 C16,19.5522847 15.5522847,20 15,20 C15.5522847,20 16,20.4477153 16,21 C16,21.5522847 15.5522847,22 15,22 L9,22 C8.44771525,22 8,21.5522847 8,21 C8,20.4477153 8.44771525,20 9,20 Z"#}
{#                                      fill="#000000"/>#}
{#                            </g>#}
{#                        </svg>#}
{#                    </span>#}
{#                    <span class="kt-menu__link-text">Documentation</span>#}
{#                </a>#}
{#            </li>#}
            <hr>
            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">
                <a href="{% url 'main:create-unit' %}" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                         <i class="fa fa-robot"></i>
                    </span>
                    <span class="kt-menu__link-text">Create - Unit</span>
                </a>
            </li>
            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">
                <a href="{% url 'main:list-unit' %}" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                         <i class="fa fa-list"></i>
                    </span>
                    <span class="kt-menu__link-text">List - Unit</span>
                </a>
            </li>
{#            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">#}
{#                <a href="{% url 'main:create-unit-code' %}" class="kt-menu__link ">#}
{#                    <span class="kt-menu__link-icon">#}
{#                         <i class="fa fa-code"></i>#}
{#                    </span>#}
{#                    <span class="kt-menu__link-text">Create - Unit code</span>#}
{#                </a>#}
{#            </li>#}
{#            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">#}
{#                <a href="{% url 'main:list-unit-code' %}" class="kt-menu__link ">#}
{#                    <span class="kt-menu__link-icon">#}
{#                         <i class="fa fa-list"></i>#}
{#                    </span>#}
{#                    <span class="kt-menu__link-text">List - Unit code</span>#}
{#                </a>#}
{#            </li>#}
            <hr>
            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">
                <a href="{% url 'main:launch-unit' %}" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="fa fa-rocket"></i>
                    </span>
                    <span class="kt-menu__link-text">Launch Unit</span>
                </a>
            </li>
            <hr>
            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">
                <a href="{% url 'main:collected-unit-data' %}" class="kt-menu__link ">
                   <span class="kt-menu__link-icon">
                        <i class="fa fa-dolly-flatbed"></i>
                    </span>
                    <span class="kt-menu__link-text">Collected Data</span>
                </a>
            </li>
            <hr>
{#            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">#}
{#                <a href="{% url 'main:support' %}" class="kt-menu__link ">#}
{#                    <span class="kt-menu__link-icon">#}
{#                        <i class="fa fa-shield-alt"></i>#}
{#                    </span>#}
{#                    <span class="kt-menu__link-text">Support</span>#}
{#                </a>#}
            </li>
        </ul>
    </div>
</div>

main/templates/parts/content-head.html
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title"><a href="{% url 'main:dashboard' %}">Dashboard</a></h3>
        <span class="kt-subheader__separator kt-subheader__separator--v"></span>
        {% if next is not None %}
            <span class="kt-subheader__desc">{{ next }}</span>
            <span class="kt-subheader__separator kt-subheader__separator--v"></span>
        {% endif %}
    </div>
    <div class="kt-subheader__toolbar"></div>
</div>

main/templates/parts/footer.html
<div class="kt-footer kt-grid__item kt-grid kt-grid--desktop kt-grid--ver-desktop" id="kt_footer">
    <div class="kt-footer__copyright">
        2020&nbsp;&copy;&nbsp;<a href="#" class="kt-link">Universal Parsing Tool</a>
    </div>
</div>

main/templates/parts/header-topbr.html
{% load static %}
<div class="kt-header__topbar">
    <!--begin: Search -->
    <!--end: Search -->
    <!--begin: User Bar -->
    <div class="kt-header__topbar-item kt-header__topbar-item--user">
        <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="0px,0px">
            <div class="kt-header__topbar-user">
                <span class="kt-header__topbar-welcome kt-hidden-mobile">Hi,</span>
                <span class="kt-header__topbar-username kt-hidden-mobile">{{ request.user.first_name }}</span>
                <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
                <span class="kt-badge kt-badge--username kt-badge--unified-success kt-badge--lg kt-badge--rounded kt-badge--bold">
                    {{ request.user.first_name|make_list|first|upper }}
                </span>
            </div>
        </div>
        <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-top-unround dropdown-menu-xl">
            <!--begin: Head -->
            <div class="kt-user-card kt-user-card--skin-dark kt-notification-item-padding-x"
                 style="background-image: url({% static "main/media/misc/bg-1.jpg" %})">
                <div class="kt-user-card__avatar">
                    {#                    <img class="kt-hidden" alt="Pic" src="assets/media/users/300_25.jpg"/>#}
                    <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
                    <span class="kt-badge kt-badge--lg kt-badge--rounded kt-badge--bold kt-font-success">
                        {{ request.user.first_name|make_list|first|upper }}
                    </span>
                </div>
                <div class="kt-user-card__name">
                    {{ request.user.first_name }} {{ request.user.last_name }}
                </div>
            </div>
            <!--end: Head -->
            <!--begin: Navigation -->
            <div class="kt-notification">
                <a href="#" class="kt-notification__item">
                    <div class="kt-notification__item-icon">
                        <i class="flaticon2-calendar-3 kt-font-success"></i>
                    </div>
                    <div class="kt-notification__item-details">
                        <div class="kt-notification__item-title kt-font-bold">
                            My Profile
                        </div>
                        <div class="kt-notification__item-time">
                            Account settings and more
                        </div>
                    </div>
                </a>
                <div class="kt-notification__custom kt-space-between">
                    <a href="{% url 'accounts:log-out' %}" class="btn btn-label btn-label-brand btn-sm btn-bold">Sign Out</a>
                </div>
            </div>
            <!--end: Navigation -->
        </div>
    </div>
    <!--end: User Bar -->
</div>

main/templates/parts/header.html
<div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed ">
    <div class="kt-header-menu-wrapper" id="kt_header_menu_wrapper">
        <div id="kt_header_menu" class="kt-header-menu kt-header-menu-mobile  kt-header-menu--layout-default "></div>
    </div>
    <!-- begin:: Header Topbar -->
    {% include 'parts/header-topbr.html' %}
    <!-- end:: Header Topbar -->
</div>

main/templates/parts/mobile-header.html
<div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
    <div class="kt-header-mobile__logo">
        <a href="demo1/index.html">
            <img alt="Logo" src="assets/media/logos/logo-light.png"/>
        </a>
    </div>
    <div class="kt-header-mobile__toolbar">
        <button class="kt-header-mobile__toggler kt-header-mobile__toggler--left" id="kt_aside_mobile_toggler">
            <span></span></button>
        <button class="kt-header-mobile__toggler" id="kt_header_mobile_toggler"><span></span></button>
        <button class="kt-header-mobile__topbar-toggler" id="kt_header_mobile_topbar_toggler"><i
                class="flaticon-more"></i></button>
    </div>
</div>

main/templates/parts/scroll-top.html
<div id="kt_scrolltop" class="kt-scrolltop">
    <i class="fa fa-arrow-up"></i>
</div>

main/templates/parts/sticky-toolbar.html
<ul class="kt-sticky-toolbar" style="margin-top: 30px;">
    <li class="kt-sticky-toolbar__item kt-sticky-toolbar__item--success" id="kt_demo_panel_toggle"
        data-toggle="kt-tooltip" title="Check out more demos" data-placement="right">
        <a href="#" class=""><i class="flaticon2-drop"></i></a>
    </li>
    <li class="kt-sticky-toolbar__item kt-sticky-toolbar__item--brand" data-toggle="kt-tooltip" title="Layout Builder"
        data-placement="left">
        <a href="https://keenthemes.com/metronic/preview/demo1/builder.html" target="_blank"><i
                class="flaticon2-gear"></i></a>
    </li>
    <li class="kt-sticky-toolbar__item kt-sticky-toolbar__item--warning" data-toggle="kt-tooltip" title="Documentation"
        data-placement="left">
        <a href="https://keenthemes.com/metronic/?page=docs" target="_blank"><i class="flaticon2-telegram-logo"></i></a>
    </li>
    <li class="kt-sticky-toolbar__item kt-sticky-toolbar__item--danger" id="kt_sticky_toolbar_chat_toggler"
        data-toggle="kt-tooltip" title="Chat Example" data-placement="left">
        <a href="#" data-toggle="modal" data-target="#kt_chat_modal"><i class="flaticon2-chat-1"></i></a>
    </li>
</ul>