main/urls.py
from django.urls import path

from .views import *

app_name = 'main'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('documentation', faq_page, name='faq'),
    path('support', support_page, name='support'),
    path('create-unit', create_unit_form, name='create-unit'),
    path('list-unit', list_unit, name='list-unit'),
    path('delete/<int:obj_id>', unit_delete, name='unit-delete'),
    path('update/<int:pk>', unit_update, name='unit-update'),
    path('launch-unit', launch_unit, name='launch-unit'),
    path('get-unit-log', get_log, name='unit-log'),
    path('launch-unit-refresh', launch_refresh, name='launch-refresh'),
    path('add-task', launch_unit_form, name='add-task'),
    path('task-update/<int:pk>', launch_unit_update, name='task-update'),
    path('collected-unit-data', collected_data, name='collected-unit-data'),
    path('collected-unit-data-show/<int:pk>', collected_data_show, name='data-show'),
]

upt_v2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from upt_v2.flower import FlowerProxyView

urlpatterns = [
    path('', include('main.urls')),
    FlowerProxyView.as_url(),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class data(models.Model):
    text = models.CharField(max_length=1024)


class Unit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256)
    createdAt = models.DateField(auto_now_add=True, blank=True, null=True)

    class Meta:
        ordering = ['id']
        indexes = [
            models.Index(fields=['nickname', 'createdAt'])
        ]


class UnitCode(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    code = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modifiedAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)


class SupportMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=32)
    text = models.TextField()
    createdAt = models.DateField(auto_now_add=True, blank=True, null=True)


class UnitData(models.Model):
    data = models.TextField(blank=True, null=True)
    unit = models.ForeignKey(
        Unit,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    createdAt = models.DateTimeField(auto_now_add=True, blank=True, null=True)

main/forms.py
from django.forms import ModelForm, forms
from django_celery_beat.models import CrontabSchedule, PeriodicTask

from main.models import *


class SupportForm(ModelForm):
    class Meta:
        model = SupportMessage
        fields = ['name', 'email', 'text']


class UnitCreateForm(ModelForm):
    class Meta:
        model = Unit
        fields = ['nickname', 'description']

    def clean_nickname(self):
        v = self.cleaned_data['nickname']

        if Unit.objects.filter(nickname=v).exists():
            raise forms.ValidationError('A Unit nickname already exists. It mast be uniq.')

        return v


class UnitFormUpdate(ModelForm):
    disabled_fields = ('nickname', 'user')

    class Meta:
        model = Unit
        fields = ['user', 'nickname', 'description']

    def __init__(self, *args, **kwargs):
        super(UnitFormUpdate, self).__init__(*args, **kwargs)
        for field in self.disabled_fields:
            self.fields[field].disabled = True


class UnitCodeForm(ModelForm):
    class Meta:
        model = UnitCode
        fields = ['code', ]


class CrontabForm(ModelForm):
    class Meta:
        model = CrontabSchedule
        fields = '__all__'


class PeriodicTaskUpdateForm(ModelForm):
    disabled_fields = ('task', )

    class Meta:
        model = PeriodicTask
        fields = ('name', 'task', 'description', 'enabled')

    def __init__(self, *args, **kwargs):
        super(PeriodicTaskUpdateForm, self).__init__(*args, **kwargs)
        for field in self.disabled_fields:
            self.fields[field].disabled = True

main/views.py
import json

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django_celery_beat.models import PeriodicTask

from logger.models import StatusLog
from .forms import *
from .spider.utils import Function
from .tasks import *


def all_subclasses(cls):
    return set(cls.__subclasses__()).union(
        [s for c in cls.__subclasses__() for s in all_subclasses(c)])


def index(request):
    return render(request, 'index.html')


def dashboard(request):
    return render(request, 'default/dashboard.html')


def faq_page(request):
    funcs = []
    for cls in all_subclasses(Function):
        funcs.append(cls().explanation())

    return render(request, 'default/faq.html', {'data': funcs})


def support_page(request):
    if request.method == 'POST':
        support = SupportForm(request.POST)
        if support.is_valid():
            action = support.save(commit=False)
            action.user = request.user
            action.save()
            messages.success(
                request,
                'Thank you! Your query sent successfully.'
            )
            return redirect(reverse('main:support'))
    else:
        support = SupportForm()

    return render(request, 'default/support.html', {'form': support})


def create_unit_form(request):
    if request.method == 'POST':
        unit = UnitCreateForm(request.POST, prefix='unit')
        code = UnitCodeForm(request.POST, prefix='code')
        if unit.is_valid() and code.is_valid():
            action = unit.save(commit=False)
            action.user = request.user
            code = code.save(commit=False)
            action.save()
            code.unit = action
            code.save()
            messages.success(
                request,
                'Yes! Your unit created successfully.'
            )
            return redirect(reverse('main:list-unit'))
    else:
        unit = UnitCreateForm(prefix='unit')
        code = UnitCodeForm(prefix='code')

    return render(request, 'bot/create_unit.html', {'form_unit': unit, 'form_code': code})


# def create_unit_code_form(request):
#     return render(request, 'bot/create_code.html')


def list_unit(request):
    if request.user.is_superuser:
        values = Unit.objects.all()
    else:
        values = Unit.objects.filter(user=request.user)
    return render(request, 'bot/list_unit.html', {'data': values})


def unit_update(request, pk: int):
    obj = get_object_or_404(Unit, pk=pk)
    unit = UnitFormUpdate(request.POST or None, instance=obj, prefix="unit")

    obj_code = get_object_or_404(UnitCode, unit=obj)
    code = UnitCodeForm(request.POST or None, instance=obj_code, prefix="code")

    if request.method == 'POST':
        if unit.is_valid() and code.is_valid():
            unit.save()
            code.save()
            messages.success(
                request,
                'Unit was updated successfully!'
            )
            return redirect(reverse('main:list-unit'))

    return render(request, 'bot/update_unit.html', {'form_unit': unit, 'form_code': code})


def unit_delete(request, obj_id: int):
    obj = get_object_or_404(Unit, pk=obj_id)
    obj.delete()

    return redirect(reverse('main:list-unit'))


def launch_unit(request):
    user = request.user
    tasks = user.profile.tasks.all()
    return render(request, 'bot/launch_unit.html', {'data': tasks})


@csrf_exempt
def get_log(request):
    if request.is_ajax():
        unit_id = request.POST.get('id')
        log_list = StatusLog.objects.filter(unit_id=unit_id)
        html = render_to_string('default/modal-log.html', {'data': log_list})
        return HttpResponse(html)


def launch_unit_update(request, pk):
    obj = get_object_or_404(PeriodicTask, pk=pk)
    task = PeriodicTaskUpdateForm(request.POST or None, instance=obj, prefix="task")

    obj_cron = get_object_or_404(CrontabSchedule, pk=obj.crontab.pk)
    cron = CrontabForm(request.POST or None, instance=obj_cron, prefix="cron")

    if request.method == 'POST':
        if task.is_valid() and cron.is_valid():
            task.save()
            cron.save()
            messages.success(
                request,
                'Task was updated successfully!'
            )
            return redirect(reverse('main:launch-unit'))

    return render(request, 'bot/launch_task_update_form.html', {'form_task': task, 'form_cron': cron})


@csrf_exempt
def launch_refresh(request):
    if request.is_ajax():
        user = request.user
        tasks = user.profile.tasks.all()
        html = render_to_string('bot/launch_table_part.html', {'data': tasks})
        return HttpResponse(html)


@csrf_exempt
def launch_unit_form(request):
    units = Unit.objects.filter(user=request.user)

    if request.is_ajax():
        unit_id = request.POST.get('id')
        unit = Unit.objects.filter(pk=unit_id)[0]
        crontab = CrontabForm()
        html = render_to_string('bot/launch_part.html', {'value': unit, 'form': crontab})
        return HttpResponse(html)
    elif request.method == 'POST':
        POST = request.POST.copy()
        task_name = POST.pop('task_name')[0]
        task_desc = POST.pop('task_desc')[0]
        unit_id = POST.pop('unit_id')[0]
        crontab = CrontabForm(POST)
        if crontab.is_valid():
            obj_crontab = crontab.save()
            create_periodic_task(request, task_name, task_desc, obj_crontab, unit_id)
            messages.success(
                request,
                'Unit task was added successfully!'
            )
            return redirect(reverse('main:launch-unit'))

    return render(request, 'bot/launch_unit_form.html', {'data': units})


def collected_data(request):
    user_id = request.user
    unit = Unit.objects.filter(user=user_id)
    return render(request, 'bot/collected_data.html', {'data': unit})


def collected_data_show(request, pk):
    unit = Unit.objects.filter(pk=pk)[0]
    values = UnitData.objects.filter(unit_id=unit.id)
    return render(request, 'bot/collected_data_show.html', {'unit': unit, 'data': values})


def create_periodic_task(request, name, description, schedule, unit_id):
    task = PeriodicTask.objects.create(
        crontab=schedule,  # we created this above.
        name=name,  # simply describes this periodic task.
        task='main.tasks.unit_task',  # name of task.
        description=description,
        args=json.dumps(unit_id),
    )
    request.user.profile.tasks.add(task)

    return task

main/templates/bot/create_code.html
{% extends 'default/dashboard.html' %}

{% block title %}Create Unit Code |{% endblock %}

{% block content-head %}
    {% include 'parts/content-head.html' with next='Create Unit Code' %}
{% endblock %}

{% block content %}
    <div class="alert alert-light" role="alert">
        <div class="alert-text">Add some code for unit
        </div>
    </div>
    <form class="form" method="post">
        <div class="card-body">
            <div class="form-group">
                <label>Unit:</label>
                <input type="text" name="unit" class="form-control form-control-solid"/>
            </div>
            <div class="form-group">
                <label>Program:</label>
                <textarea type="text" name="program" rows="10" class="form-control form-control-solid"></textarea>
            </div>
        </div>
        <div class="card-footer">
            <button type="reset" class="btn btn-primary mr-2">Add</button>
        </div>

    </form>
{% endblock %}

main/templates/bot/launch_unit.html
{% extends 'default/dashboard.html' %}

{% block title %}Launch Unit |{% endblock %}

{% block content-head %}
    {% include 'parts/content-head.html' with next='Launch Unit' %}
{% endblock %}

{% block content %}
    {% if messages %}
        <div class="alert alert-custom alert-success fade show mb-5" role="alert">
            <div class="alert-icon">
                <i class="flaticon-like"></i>
            </div>
            {% for msg in messages %}
                <div class="alert-text">{{ msg }}</div>
                <p {% if msg.tags %} class="{{ msg.tags }}"{% endif %}></p>
            {% endfor %}
            <div class="alert-close">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">
                            <i class="flaticon2-cross"></i>
                        </span>
                </button>
            </div>
        </div>
    {% endif %}

    <div class="card card-custom gutter-b">
        <!--begin::Header-->
        <div class="card-header border-0 py-5">
            <h3 class="card-title align-items-start flex-column">
                <span class="card-label font-weight-bolder text-dark">Tasks</span><br><br>
                <span class="text-muted mt-3 font-weight-bold font-size-sm">List of your tasks</span><br>
                <span class="text-muted mt-3 font-weight-bold font-size-sm">After adding your task automatically will run by your criteria</span>
            </h3>
            <br>
            <div class="card-toolbar">
                <a href="{% url 'main:add-task' %}" class="btn btn-success font-weight-bolder font-size-sm">
                    <i aria-hidden="true" class="fas fa-plus"></i>Add New Task</a>
                <a href="#" id="refresh" class="btn btn-info font-weight-bolder font-size-sm">
                    <i aria-hidden="true" class="flaticon-refresh"></i>Refresh</a>
            </div>
        </div>
        <!--end::Header-->
        <!--begin::Body-->
        <div class="card-body py-0">
            <div id="error"></div>
            <!--begin::Table-->
            <div class="table-responsive" id="table">
                <table class="table table-head-custom table-vertical-center" id="kt_advance_table_widget_1">
                    <thead>
                    <tr class="text-left">
                        <th class="pr-0" style="width: 200px">Name</th>
                        <th style="min-width: 150px">Task</th>
                        <th style="min-width: 150px">Description</th>
                        <th style="min-width: 150px">Total run count</th>
                        <th style="min-width: 150px">Cron</th>
                        <th style="min-width: 150px">Last run</th>
                        <th style="min-width: 150px">Enabled</th>
                        <th style="min-width: 150px">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in data %}
                        <tr>
                            <td>
                                <span class="text-dark-75 font-weight-bolder text-hover-primary mb-1 font-size-lg">{{ item.name }}</span>
                            </td>
                            <td>
                                <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ item.task }}</span>
                            </td>
                            <td>
                                <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ item.description|slice:"16" }}
                                    {% if item.description|length > 16 %}...{% endif %}</span>
                            </td>
                            <td>
                                <div class="d-flex flex-column w-100 mr-2">
                                    <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ item.total_run_count }}</span>
                                </div>
                            </td>
                            <td>
                                <div class="d-flex flex-column w-100 mr-2">
                                    <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ item.crontab }}</span>
                                </div>
                            </td>
                            <td>
                                <div class="d-flex flex-column w-100 mr-2">
                                    <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ item.last_run_at }}</span>
                                </div>
                            </td>
                            <td>
                                <div class="d-flex flex-column w-100 mr-2">
                                    <span>{{ item.enabled }}</span>
                                </div>
                            </td>
                            <td>
                                <a href="{% url 'main:task-update' pk=item.id %}" title="Edit"
                                   class="btn btn-icon btn-light btn-sm mx-3">
                                    <span class="svg-icon svg-icon-md svg-icon-primary">
                                        <!--begin::Svg Icon | path:/metronic/theme/html/demo1/dist/assets/media/svg/icons/Communication/Write.svg-->
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             xmlns:xlink="http://www.w3.org/1999/xlink"
                                             width="24px" height="24px" viewBox="0 0 24 24"
                                             version="1.1">
                                            <g stroke="none" stroke-width="1" fill="none"
                                               fill-rule="evenodd">
                                                <rect x="0" y="0" width="24"
                                                      height="24"></rect>
                                                <path d="M12.2674799,18.2323597 L12.0084872,5.45852451 C12.0004303,5.06114792 12.1504154,4.6768183 12.4255037,4.38993949 L15.0030167,1.70195304 L17.5910752,4.40093695 C17.8599071,4.6812911 18.0095067,5.05499603 18.0083938,5.44341307 L17.9718262,18.2062508 C17.9694575,19.0329966 17.2985816,19.701953 16.4718324,19.701953 L13.7671717,19.701953 C12.9505952,19.701953 12.2840328,19.0487684 12.2674799,18.2323597 Z"
                                                      fill="#000000" fill-rule="nonzero"
                                                      transform="translate(14.701953, 10.701953) rotate(-135.000000) translate(-14.701953, -10.701953)"></path>
                                                <path d="M12.9,2 C13.4522847,2 13.9,2.44771525 13.9,3 C13.9,3.55228475 13.4522847,4 12.9,4 L6,4 C4.8954305,4 4,4.8954305 4,6 L4,18 C4,19.1045695 4.8954305,20 6,20 L18,20 C19.1045695,20 20,19.1045695 20,18 L20,13 C20,12.4477153 20.4477153,12 21,12 C21.5522847,12 22,12.4477153 22,13 L22,18 C22,20.209139 20.209139,22 18,22 L6,22 C3.790861,22 2,20.209139 2,18 L2,6 C2,3.790861 3.790861,2 6,2 L12.9,2 Z"
                                                      fill="#000000" fill-rule="nonzero"
                                                      opacity="0.3"></path>
                                            </g>
                                        </svg>
                                        <!--end::Svg Icon-->
                                    </span>
                                </a>
                                <a href="#" title="Log view" onclick="log(this); return false;" data-id='{{ item.args|slice:"1:-1" }}'
                                   class="btn btn-icon btn-light-primary mr-2"
                                   id="modal-log">
                                    <i class="flaticon2-sheet"></i>
                                </a>
                            </td>
                        </tr>
                    {% empty %}
                        <td class="text-center font-weight-bolder" colspan="5">Sorry, you have not any tasks</td>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <!--end::Table-->
        </div>
        <!--end::Body-->
    </div>

    <!-- Modal-->
    <div class="modal fade" id="logModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
{% endblock %}

{% block custom-script %}
    <script>
        function log(t) {

            let unit_id = $(t).data("id");
            console.log(unit_id);
            $.ajax({
                url: '{% url 'main:unit-log' %}', // the endpoint
                type: "POST", // http method
                data: {
                    id: unit_id
                },

                // handle a successful response
                success: function (data) {
                    $('div#logModal').html(data)
                    $('#logModal').modal('show')
                },

                // handle a non-successful response
                error: function (xhr, errmsg, err) {
                    $('div#error').html("<div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">" +
                        "<strong id=\"error\">" + JSON.parse(xhr.responseText)['error'] + "</strong>" +
                        "            <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">" +
                        "                <span aria-hidden=\"true\">&times;</span>" +
                        "            </button>" +
                        "        </div>"); // add the error to the dom
                }
            })
        };
        $('#refresh').on('click', function (event) {
            event.preventDefault()

            $.ajax({
                url: '{% url 'main:launch-refresh' %}', // the endpoint
                type: "POST", // http method

                // handle a successful response
                success: function (data) {
                    $('div#table').html(data)
                },

                // handle a non-successful response
                error: function (xhr, errmsg, err) {
                    $('div#error').html("<div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">" +
                        "<strong id=\"error\">" + JSON.parse(xhr.responseText)['error'] + "</strong>" +
                        "            <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">" +
                        "                <span aria-hidden=\"true\">&times;</span>" +
                        "            </button>" +
                        "        </div>"); // add the error to the dom
                }
            })
        });
    </script>
{% endblock %}

main/templates/bot/list_code.html
{% extends 'default/dashboard.html' %}

{% block title %}List Unit Code |{% endblock %}

{% block content-head %}
    {% include 'parts/content-head.html' with next='List Unit Code' %}
{% endblock %}

main/templates/bot/list_unit.html
{% extends 'default/dashboard.html' %}

{% block title %}List Unit|{% endblock %}

{% block content-head %}
    {% include 'parts/content-head.html' with next='Units list' %}
{% endblock %}

{% block content %}
    {% if messages %}
        <div class="alert alert-custom alert-success fade show mb-5" role="alert">
            <div class="alert-icon">
                <i class="flaticon-like"></i>
            </div>
            {% for msg in messages %}
                <div class="alert-text">{{ msg }}</div>
                <p {% if msg.tags %} class="{{ msg.tags }}"{% endif %}></p>
            {% endfor %}
            <div class="alert-close">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">
                            <i class="flaticon2-cross"></i>
                        </span>
                </button>
            </div>
        </div>
    {% endif %}

    <div class="card card-custom gutter-b">
        <!--begin::Header-->
        <div class="card-header border-0 py-5">
            <h3 class="card-title align-items-start flex-column">
                <span class="card-label font-weight-bolder text-dark">Units</span><br><br>
                <span class="text-muted mt-3 font-weight-bold font-size-sm">List of your units</span>
            </h3>
            <br>
            <div class="card-toolbar">
                <a href="{% url 'main:create-unit' %}" class="btn btn-success font-weight-bolder font-size-sm">
                    <i aria-hidden="true" class="fas fa-plus"></i>Add New Unit</a>
            </div>
        </div>
        <!--end::Header-->
        <!--begin::Body-->
        <div class="card-body py-0">
            <!--begin::Table-->
            <div class="table-responsive">
                <table class="table table-head-custom table-vertical-center" id="kt_advance_table_widget_1">
                    <thead>
                    <tr class="text-left">
                        {% if request.user.is_superuser %}
                            <th class="pr-0" style="width: 200px">User</th>
                        {% endif %}
                        <th style="min-width: 150px">Nickname</th>
                        <th style="min-width: 150px">Date creation</th>
                        <th style="min-width: 150px">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in data %}
                        <tr>
                            {% if request.user.is_superuser %}
                                <td>
                                    <span class="text-dark-75 font-weight-bolder text-hover-primary mb-1 font-size-lg">{{ item.user.username }}</span>
                                </td>
                            {% endif %}
                            <td>
                                <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ item.nickname }}</span>
                                <span class="text-muted font-weight-bold">{{ item.description|slice:"16" }}{% if item.description|length > 16 %}...{% endif %}</span>
                            </td>
                            <td>
                                <div class="d-flex flex-column w-100 mr-2">
                                    <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ item.createdAt }}</span>
                                </div>
                            </td>
                            <td >
                                <a href="{% url 'main:unit-update' pk=item.id  %}" class="btn btn-icon btn-light btn-sm mx-3">
                                <span class="svg-icon svg-icon-md svg-icon-primary">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         xmlns:xlink="http://www.w3.org/1999/xlink"
                                         width="24px" height="24px" viewBox="0 0 24 24"
                                         version="1.1">
                                        <g stroke="none" stroke-width="1" fill="none"
                                           fill-rule="evenodd">
                                            <rect x="0" y="0" width="24"
                                                  height="24"></rect>
                                            <path d="M12.2674799,18.2323597 L12.0084872,5.45852451 C12.0004303,5.06114792 12.1504154,4.6768183 12.4255037,4.38993949 L15.0030167,1.70195304 L17.5910752,4.40093695 C17.8599071,4.6812911 18.0095067,5.05499603 18.0083938,5.44341307 L17.9718262,18.2062508 C17.9694575,19.0329966 17.2985816,19.701953 16.4718324,19.701953 L13.7671717,19.701953 C12.9505952,19.701953 12.2840328,19.0487684 12.2674799,18.2323597 Z"
                                                  fill="#000000" fill-rule="nonzero"
                                                  transform="translate(14.701953, 10.701953) rotate(-135.000000) translate(-14.701953, -10.701953)"></path>
                                            <path d="M12.9,2 C13.4522847,2 13.9,2.44771525 13.9,3 C13.9,3.55228475 13.4522847,4 12.9,4 L6,4 C4.8954305,4 4,4.8954305 4,6 L4,18 C4,19.1045695 4.8954305,20 6,20 L18,20 C19.1045695,20 20,19.1045695 20,18 L20,13 C20,12.4477153 20.4477153,12 21,12 C21.5522847,12 22,12.4477153 22,13 L22,18 C22,20.209139 20.209139,22 18,22 L6,22 C3.790861,22 2,20.209139 2,18 L2,6 C2,3.790861 3.790861,2 6,2 L12.9,2 Z"
                                                  fill="#000000" fill-rule="nonzero"
                                                  opacity="0.3"></path>
                                        </g>
                                    </svg>
                                </span>
                                </a>
                                <a href="{% url 'main:unit-delete' obj_id=item.id  %}" class="btn btn-icon btn-light btn-sm">
                                <span class="svg-icon svg-icon-md svg-icon-primary">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         xmlns:xlink="http://www.w3.org/1999/xlink"
                                         width="24px" height="24px" viewBox="0 0 24 24"
                                         version="1.1">
                                        <g stroke="none" stroke-width="1" fill="none"
                                           fill-rule="evenodd">
                                            <rect x="0" y="0" width="24"
                                                  height="24"></rect>
                                            <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z"
                                                  fill="#000000"
                                                  fill-rule="nonzero"></path>
                                            <path d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z"
                                                  fill="#000000" opacity="0.3"></path>
                                        </g>
                                    </svg>
                                </span>
                                </a>
                            </td>
                        </tr>
                    {% empty %}
                        <td class="text-center font-weight-bolder" colspan="5">Sorry, you have not units</td>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!--end::Table-->
        </div>
        <!--end::Body-->
    </div>
{% endblock %}