accounts/urls.py
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('log-out', log_out, name="log-out"),
    path('sign-in', sign_in, name="sign-in"),
    path('sign-up', signup, name="sign-up"),
    # path('profile', profile, name="profile"),
    path('forgot-password', forgot_password, name="forgot-password"),
    path('password/reset_confirm/<slug:uidb64>/<slug:token>', password_reset_confirm, name="confirm_reset_password"),
    path('activate/<slug:uidb64>/<slug:token>', activate, name="activate"),
]

main/urls.py
from django.urls import path

from .views import *

app_name = 'main'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('documentation', faq_page, name='faq'),
    path('support', support_page, name='support'),
    path('create-unit', create_unit_form, name='create-unit'),
    path('list-unit', list_unit, name='list-unit'),
    path('delete/<int:obj_id>', unit_delete, name='unit-delete'),
    path('update/<int:pk>', unit_update, name='unit-update'),
    path('launch-unit', launch_unit, name='launch-unit'),
    path('get-unit-log', get_log, name='unit-log'),
    path('launch-unit-refresh', launch_refresh, name='launch-refresh'),
    path('add-task', launch_unit_form, name='add-task'),
    path('task-update/<int:pk>', launch_unit_update, name='task-update'),
    path('collected-unit-data', collected_data, name='collected-unit-data'),
    path('collected-unit-data-show/<int:pk>', collected_data_show, name='data-show'),
]

upt_v2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from upt_v2.flower import FlowerProxyView

urlpatterns = [
    path('', include('main.urls')),
    FlowerProxyView.as_url(),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_celery_beat.models import PeriodicTask


# Create your models here.

class Profile(models.Model):
    ACC_TYPE_CHOICES = (
        (0, 'Trial'),
        (1, 'Full'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=32, blank=True)
    # avatar = models.ImageField(upload_to='', blank=True)
    api_key = models.CharField(max_length=128, blank=True)
    tasks = models.ManyToManyField(PeriodicTask)
    acc_type = models.CharField(max_length=1, choices=ACC_TYPE_CHOICES, default=ACC_TYPE_CHOICES[0][0])
    expired_at = models.DateTimeField(default=datetime.datetime.now() + datetime.timedelta(days=7))


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

accounts/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.core.validators import validate_email
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .token_generator import account_activation_token


def return_error_msg(msg, status=400):
    resp = JsonResponse({"success": False, "msg": msg})
    resp.status_code = status
    return resp


def signup(request):
    if request.is_ajax():
        print(request.POST.get('username'))
        if User.objects.filter(username=request.POST.get('username')).exists():
            return return_error_msg('Sorry, but username already exist. Try to change it.')
        else:
            user = User.objects.create(
                first_name=request.POST.get('name'),
                last_name=request.POST.get('surname'),
                username=request.POST.get('username'),
                password=make_password(request.POST.get('password')),
                email=request.POST.get('email'),
                is_active=False,
            )
            message = render_to_string('parts/activate_account_message.html', {
                'user': user,
                'domain': get_current_site(request),
                'uid': urlsafe_base64_encode(force_bytes(user.id)),
                'token': account_activation_token.make_token(user),
            })
            to_email = request.POST.get('email')
            EmailMessage('Activate Your Account', message, to=[to_email]).send()
            return JsonResponse({"message": "OK"})
    else:
        return return_error_msg('Bad request')


def sign_in(request):
    if request.method == 'GET':
        return render(request, 'index.html')
    elif request.is_ajax():
        username = request.POST.get('username')
        password = request.POST.get('password')
        if request.POST.get('remember') is None:
            request.session.set_expiry(0)

        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
            # args['profile'] = user
            return redirect('/')
        else:
            # args['login_error'] = 'User not found!'
            return return_error_msg('Username or/and password are incorrect.')
    else:
        return return_error_msg('Bad request')


def log_out(request):
    logout(request)
    return redirect('/')


def email_validation(email):
    try:
        validate_email(email)
        return True
    except ValidationError:
        return False


def forgot_password(request):
    if request.is_ajax():
        u_email = request.POST.get('email')
        if email_validation(u_email):
            user = User.objects.filter(email=u_email)
            if user.exists():
                user = user.first()
                message = render_to_string('parts/reset_password_message.html', {
                    'domain': get_current_site(request),
                    'uid': urlsafe_base64_encode(force_bytes(user.id)),
                    'user': user,
                    'token': default_token_generator.make_token(user),
                })
                EmailMessage('Password recovering', message, to=[u_email]).send()
                return JsonResponse({"message": "OK"})
        else:
            return JsonResponse({"message": "OK"})  # little trolling


def activate(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return render(request, 'index.html', {
            'alert_msg': 'Your account has been activate successfully!',
            'alert_type': 'success'
        })
    else:
        return render(request, 'index.html', {
            'alert_msg': 'Activation link is invalid!',
            'alert_type': 'danger'
        })


def password_reset_confirm(request, uidb64, token):
    if request.method == 'GET':
        return render(request, 'parts/change_password.html')
    elif request.is_ajax():
        try:
            uid = force_bytes(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            new_password = request.POST.get('password')
            user.set_password(new_password)
            user.save()
            return render(request, 'index.html', {
                'alert_msg': 'Your password has been updated successfully!',
                'alert_type': 'success'
            })
        else:
            return render(request, 'index.html', {
                'alert_msg': 'Activation link is invalid!',
                'alert_type': 'danger'
            })
    else:
        return render(request, 'index.html', {
            'alert_msg': 'Bad request',
            'alert_type': 'danger'
        })

accounts/templates/parts/activate_account_message.html
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm your registration,
    http://{{ domain.domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/parts/change_password.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Recovering password |{% endblock %}

{% block custom-style %}
    <link href="{% static "main/css/demo1/pages/general/login/login-6.css" %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block body-cls %}class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed
    kt-header-mobile--fixed kt-subheader--fixed kt-subheader--enabled kt-subheader--solid kt-aside--enabled
    kt-aside--fixed kt-page--loading"{% endblock %}

{% block body %}
    <div class="kt-grid kt-grid--ver kt-grid--root">
        <div class="kt-grid kt-grid--hor kt-grid--root  kt-login kt-login--v6 kt-login--signin" id="kt_login">
            <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--desktop kt-grid--ver-desktop kt-grid--hor-tablet-and-mobile">
                <div class="kt-grid__item  kt-grid__item--order-tablet-and-mobile-2  kt-grid kt-grid--hor kt-login__aside">
                    <div class="kt-login__wrapper">
                        <div class="kt-login__container">
                            <div class="kt-login__body">
                                <div class="kt-login__forgot__new">
                                    <div class="kt-login__head">
                                        <h3 class="kt-login__title">Forgotten Password ?</h3>
                                        <div class="kt-login__desc">Enter new password:</div>
                                    </div>
                                    <div class="kt-login__form">
                                        <form class="kt-form" action="">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input class="form-control" type="password" placeholder="Password"
                                                       name="password"
                                                       id="password" autocomplete="off">
                                            </div>
                                            <div class="form-group">
                                                <input class="form-control" type="password" placeholder="Password"
                                                       name="rpassword"
                                                       id="rpassword" autocomplete="off">
                                            </div>
                                            <div class="kt-login__actions">
                                                <button id="kt_login_forgot_new"
                                                        class="btn btn-brand btn-pill btn-elevate">Request
                                                </button>
                                                <button id="kt_login_forgot_cancel"
                                                        class="btn btn-outline-brand btn-pill">
                                                    Cancel
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="kt-grid__item kt-grid__item--fluid kt-grid__item--center kt-grid kt-grid--ver kt-login__content"
                     style="background-image: url({% static "main/media/bg/abstract.jpg" %});">
                    <div class="kt-login__section">
                        <div class="kt-login__block">
                            <h3 class="kt-login__title">Join Our System</h3>
                            <div class="kt-login__desc"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom-script %}
    <script type="text/javascript" src="{% static 'main/js/demo1/pages/login/change-password.js' %}"></script>
{% endblock %}

accounts/templates/parts/forgot_password.html
<div class="kt-login__forgot">
    <div class="kt-login__head">
        <h3 class="kt-login__title">Forgotten Password ?</h3>
        <div class="kt-login__desc">Enter your email to reset your password:</div>
    </div>
    <div class="kt-login__form">
        <form class="kt-form" action="">
            {% csrf_token %}

            <div class="form-group">
                <input class="form-control" type="text" placeholder="Email" name="email"
                       id="kt_email" autocomplete="off">
            </div>
            <div class="kt-login__actions">
                <button id="kt_login_forgot_submit"
                        class="btn btn-brand btn-pill btn-elevate">Request
                </button>
                <button id="kt_login_forgot_cancel" class="btn btn-outline-brand btn-pill">
                    Cancel
                </button>
            </div>
        </form>
    </div>
</div>

accounts/templates/parts/login.html
<div class="kt-login__signin">
    <div class="kt-login__head">
        <h3 class="kt-login__title">Sign In</h3>
    </div>
    <div class="kt-login__form">
        <form class="kt-form" action="">
            {% csrf_token %}

            <div class="form-group">
                <input class="form-control" type="text" placeholder="Username" name="username">
            </div>
            <div class="form-group">
                <input class="form-control form-control-last" type="password"
                       placeholder="Password" name="password">
            </div>
            <div class="kt-login__extra">
                <label class="kt-checkbox">
                    <input type="checkbox" name="remember"> Remember me
                    <span></span>
                </label>
                <a href="javascript:;" id="kt_login_forgot">Forget Password ?</a>
            </div>
            <div class="kt-login__actions">
                <button id="kt_login_signin_submit"
                        class="btn btn-brand btn-pill btn-elevate">Sign In
                </button>
            </div>
        </form>
    </div>
</div>

accounts/templates/parts/reset_password_message.html
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to change yours password!,
    http://{{ domain.domain }}{% url 'accounts:confirm_reset_password' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/parts/signup.html
<div class="kt-login__signup">
    <div class="kt-login__head">
        <h3 class="kt-login__title">Sign Up</h3>
        <div class="kt-login__desc">Enter your details to create your account:</div>
    </div>
    <div class="kt-login__form">
        <form class="kt-form" action="">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Name"
                       name="name">
            </div>
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Surname"
                       name="surname">
            </div>
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Username"
                       name="username">
            </div>
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Email" name="email"
                       autocomplete="off">
            </div>
            <div class="form-group">
                <input class="form-control" id="password" type="password" placeholder="Password"
                       name="password">
            </div>
            <div class="form-group">
                <input class="form-control form-control-last" type="password"
                       placeholder="Confirm Password" name="rpassword">
            </div>
            <div class="kt-login__extra">
                <label class="kt-checkbox">
                    <input type="checkbox" name="agree"> I Agree the <a href="#">terms and
                    conditions</a>.
                    <span></span>
                </label>
            </div>
            <div class="kt-login__actions">
                <button id="kt_login_signup_submit"
                        class="btn btn-brand btn-pill btn-elevate" type="submit">Sign Up
                </button>
                <button id="kt_login_signup_cancel" class="btn btn-outline-brand btn-pill">
                    Cancel
                </button>
            </div>
        </form>
    </div>
</div>